<footer class="py-8 px-6 bg-blue-700 text-white">
    <div class="text-center">
        <img class="mx-auto" src="./logo/APOCRAT-weiss.svg" width="150"/>
        <div class="mt-4">
            BIZ - Heinrich Schneidmadl Str. 15<br/>
            3100 St. Pölten<br/>
            <a class="underline hover:no-underline hover:text-grey-500" href="mailto:office@apocrat.at">Office@apocrat.at</a>
        </div>
        <div class="mt-4">
            <a class="block underline hover:no-underline hover:text-grey-500" href="/datenschutz">Datenschutz</a>
            <a class="block underline hover:no-underline hover:text-grey-500" href="/impressum">Impressum</a>
        </div>
    </div>

    <!--<div>TodoL</div>
    <ul>
        <li>/</li>
        <li>/teamS</li>
        <li>/datenschutz</li>
        <li>/impressum</li>
        <li>keynote am 10.12, deadline ca. 8.12.</li>
    </ul>-->
</footer>