<div class="bg-blue-700 py-4">
    <div class="container text-white">
        <div class="flex justify-between">
            <a class="z-50" href="/"><img class="" src="./logo/APOCRAT-weiss.svg" style="width: 150px;"/></a>
            <ul class="absolute md:static hidden md:flex left-0 right-0 top-0 bottom-0 bg-blue-700 z-10 p-12 md:p-0 flex-col md:flex-row text-center js-navbar--toggle">
                <li class="inline-block mt-12 md:mt-0">
                    <a class="text-xl md:text-base text-white mx-1 md:mx-4 hover:underline hover:text-grey-500" href="/privatpersonen">Für Privatpersonen</a>
                </li>
                <li class="inline-block mt-8 md:mt-0">
                    <a class="text-xl md:text-base text-white mx-1 md:mx-4 hover:underline hover:text-grey-500" href="/ueber-uns">Über uns</a>
                </li>
            </ul>
            <button class="md:hidden mr-2" onclick="openNavbar();">
                <img class="" src="./icon/menu.svg" />
            </button>
            <button class="hidden js-navbar--toggle" onclick="closeNavbar();">
                <img class="absolute right-3 top-3 z-10" src="./icon/close.svg" />
            </button>
        </div>
    </div>
</div>