<div class="bg-blue-700 py-4">
    <div class="container text-white">
        <div class="flex justify-between">
            <a href="/"><img class="navbar__logo" src="./logo/APOCRAT-weiss.svg" width="150"/></a>
            <ul class="text-right">
                <li class="inline-block">
                    <a class="text-white mx-4 hover:underline hover:text-grey-500" href="/privatpersonen">Für Privatpersonen</a>
                </li>
                <li class="inline-block">
                    <a class="text-white mx-4 hover:underline hover:text-grey-500" href="/ueber-uns">Über uns</a>
                </li>
            </ul>
        </div>
    </div>
</div>