<!-- Slideshow container -->
<div class="slideshow-container">

    <!-- Full-width images with number and caption text -->
    <div class="mySlides fade">
        <div class="w-1/2 mx-auto text-center">
            <img class="mx-auto" src="/icon/small-slider/001-printing.svg" width="136" height="136"/>
            <div class="mt-6 mb-2 text-blue-300 font-bold">Drucker:</div>
            <p class="w-max-s md:w-max-xs">
                Bequem vom Sofa oder sogar unterwegs drucken? Super!
                Auch der Hersteller freut sich. Immerhin bekommt er deine gedruckten Dateien.
            </p>
        </div>
    </div>

    <div class="mySlides fade">
        <div class="w-1/2 mx-auto text-center">
            <img class="mx-auto" src="/icon/small-slider/002-vaccum-cleaner.svg" width="136" height="136"/>
            <div class="mt-6 mb-2 text-blue-300 font-bold">Staubsaugroboter:</div>
            <p class="w-max-s md:w-max-xs">
                Staubsaugroboter erstellen Karten der Wohnung, um besser navigieren zu können.
                Wer die Karten noch bekommt? Richtig geraten: der Hersteller und Meistbietende.
            </p>
        </div>
    </div>

    <div class="mySlides fade">
        <div class="w-1/2 mx-auto text-center">
            <img class="mx-auto" src="/icon/small-slider/003-radio.svg" width="136" height="136"/>
            <div class="mt-6 mb-2 text-blue-300 font-bold">Internetradio:</div>
            <p class="w-max-s md:w-max-xs">
                Auch dieses Gerät kommuniziert über das Internet und öffnet die Tür für Angreifer.
                Zudem wird dein Musikgeschmack an den Hersteller übermittelt.
            </p>
        </div>
    </div>

    <div class="mySlides fade">
        <div class="w-1/2 mx-auto text-center">
            <img class="mx-auto" src="/icon/small-slider/005-smart-tv.svg" width="136" height="136"/>
            <div class="mt-6 mb-2 text-blue-300 font-bold">Smart TV:</div>
            <p class="w-max-s md:w-max-xs">
                Über 50% der Haushalte in AT & DE besitzen einen Smart TV.<br/>
                Mit Kameras ausgerüstet stellt dieses Gerät ein beliebtes Ziel für Hacker dar.
            </p>
        </div>
    </div>

    <div class="mySlides fade">
        <div class="w-1/2 mx-auto text-center">
            <img class="mx-auto" src="/icon/small-slider/004-speaker.svg" width="136" height="136"/>
            <div class="mt-6 mb-2 text-blue-300 font-bold">Sprachassistent:</div>
            <p class="w-max-s md:w-max-xs">
                Dein Sprachassistent arbeitet dauerhaft über das Internet.
                Leider hört er absolut alles, was im Raum passiert.
                Wie soll er denn sonst auf seine Aufwachkommandos hören?
            </p>
        </div>
    </div>

    <!-- Next and previous buttons -->
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>
<br>

<!-- The dots/circles -->
<div style="text-align:center">
    <span class="dot" onclick="currentSlide(1)"></span>
    <span class="dot" onclick="currentSlide(2)"></span>
    <span class="dot" onclick="currentSlide(3)"></span>
    <span class="dot" onclick="currentSlide(4)"></span>
    <span class="dot" onclick="currentSlide(5)"></span>
</div>